name: github_users
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  http: ^1.3.0
  flutter_localizations:
    sdk: flutter
  intl: any
  equatable: ^2.0.7
  flutter_dotenv: ^5.2.1
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true 
  assets:
    - config/config.env

